# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UseNode@2
  inputs:
    versionSpec: '14.x'
  displayName: 'Set up Node.js'

- script: npm install
  displayName: 'Install dependencies'

- script: npm run lint
  displayName: 'Run Linting'

- script: npm test
  displayName: 'Run Tests'

- task: PublishBuildArtifacts@1
  inputs:
    artifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Artifacts'

# Example Deployment Step (depends on your deployment target)
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'YOUR_AZURE_SUBSCRIPTION_NAME'
    appName: 'YOUR_APP_NAME'
    package: $(System.DefaultWorkingDirectory)/drop
  displayName: 'Deploy to Azure Web App'
